sudo: required
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.1
before_install:
  - yes | sdkmanager --licenses
  – chmod +x gradlew
script:
  - ./gradlew test
